name: run-test

on: [push]

jobs:
  test:
    name: Test on Python 3.12.0
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0

    - name: Run tests with pytest
      run: python -m unittest test_leapyear.py

