name: run-test

on: [push]

jobs:
  test:
    name: Test on Python 3.12.0
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0

    - name: List files in the directory
      run: ls

    - name: List repository contents
      run: ls $GITHUB_WORKSPACE

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests with pytest
      run: pytest --junitxml=test-results/test-results.xml

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results
